CREATE TABLE IF NOT EXISTS patients (
  id uuid PRIMARY KEY,
  name text NOT NULL,
  email text NOT NULL,
  phone text NOT NULL,
  birth_date date,
  gender text,
  address text,
  occupation text,
  emergency_contact_name text,
  emergency_contact_number text,
  primary_physician text,
  insurance_provider text,
  insurance_policy_number text,
  allergies text,
  current_medication text,
  family_medical_history text,
  past_medical_history text,
  identification_type text,
  identification_number text,
  identification_document_path text,
  treatment_consent boolean DEFAULT false,
  disclosure_consent boolean DEFAULT false,
  privacy_consent boolean DEFAULT false,
  stage text NOT NULL DEFAULT 'draft',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS appointments (
  id uuid PRIMARY KEY,
  patient_id uuid NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  patient_name text NOT NULL,
  patient_email text NOT NULL,
  patient_phone text NOT NULL,
  doctor_name text NOT NULL,
  schedule_at timestamptz NOT NULL,
  reason text NOT NULL,
  note text,
  status text NOT NULL DEFAULT 'pending',
  cancellation_reason text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
